# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
  name: 'Default'
  demands:
    - agent.name -equals DESKTOP-MV3RMI5

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    npm --version
  displayName: 'npm version'

- task: UseNode@1
  inputs:
      version: '18.x'

- script: |
    npm install
    npm test
  displayName: 'Instalar dependencias y ejecutar tests'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students(3efca608-9871-495c-ac85-7be2286ab418)'
    appType: 'webAppLinux'
    appName: 'pipeline'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'NODE|18-lts'
    startUpCommand: 'npm start'